pull_request_rules:
  - name: merge automated metals update PRs on CI success
    conditions:
      - author=gvolpe
      - title~=(?i)Update Metals to
      - check-success~=build
    actions:
      merge:
        method: merge
